name: Imp3
dependencies:
- _nb_ext_conf=0.3.0=py35_0
- anaconda-client=1.5.1=py35_0
- anaconda=custom=py35_0
- bzip2=1.0.6=3
- cairo=1.12.18=6
- cffi=1.7.0=py35_0
- cloog=0.18.0=0
- clyent=1.2.2=py35_0
- cryptography=1.5=py35_0
- curl=7.49.0=1
- cycler=0.10.0=py35_0
- dbus=1.10.10=0
- decorator=4.0.10=py35_0
- docutils=0.12=py35_2
- entrypoints=0.2.2=py35_0
- expat=2.1.0=0
- filechunkio=1.6=py35_0
- fontconfig=2.11.1=6
- freetype=2.5.5=1
- ftputil=3.2=py35_0
- gcc=4.8.5=6
- glib=2.43.0=2
- gmp=5.1.2=2
- gsl=2.1=1
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- harfbuzz=0.9.39=1
- icu=54.1=0
- idna=2.1=py35_0
- ipykernel=4.5.0=py35_0
- ipython=5.1.0=py35_0
- ipython_genutils=0.1.0=py35_0
- ipywidgets=5.2.2=py35_0
- isl=0.12.2=0
- jbig=2.1=0
- jinja2=2.8=py35_1
- jpeg=8d=1
- jsonschema=2.5.1=py35_0
- jupyter=1.0.0=py35_3
- jupyter_client=4.4.0=py35_0
- jupyter_console=5.0.0=py35_0
- jupyter_core=4.2.0=py35_0
- libffi=3.2.1=0
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libpng=1.6.22=0
- libsodium=1.0.10=0
- libtiff=4.0.6=2
- libxcb=1.12=0
- libxml2=2.9.2=0
- markupsafe=0.23=py35_2
- matplotlib=1.5.3=np111py35_0
- mistune=0.7.3=py35_0
- mkl=11.3.3=0
- mpc=1.0.1=0
- mpfr=3.1.2=0
- nb_anacondacloud=1.2.0=py35_0
- nb_conda=2.0.0=py35_0
- nb_conda_kernels=2.0.0=py35_0
- nbconvert=4.2.0=py35_0
- nbformat=4.1.0=py35_0
- nbpresent=3.0.2=py35_0
- ncurses=5.9=8
- networkx=1.11=py35_0
- notebook=4.2.3=py35_0
- numpy=1.11.1=py35_0
- openssl=1.0.2j=0
- pandas=0.18.1=np111py35_0
- pango=1.39.0=1
- paramiko=2.0.2=py35_0
- path.py=8.2.1=py35_0
- pcre=8.39=0
- pexpect=4.0.1=py35_0
- pickleshare=0.7.4=py35_0
- pip=8.1.2=py35_0
- pixman=0.32.6=0
- prompt_toolkit=1.0.3=py35_0
- ptyprocess=0.5.1=py35_0
- pyasn1=0.1.9=py35_0
- pycparser=2.14=py35_1
- pygments=2.1.3=py35_0
- pyparsing=2.1.4=py35_0
- pyqt=5.6.0=py35_0
- pysftp=0.2.8=py35_0
- python=3.5.2=0
- python-dateutil=2.5.3=py35_0
- pytz=2016.6.1=py35_0
- pyyaml=3.12=py35_0
- pyzmq=15.4.0=py35_0
- qt=5.6.0=0
- qtconsole=4.2.1=py35_1
- r=3.1.2=2
- r-base=3.3.1=3
- r-colorspace=1.2_6=r3.3.1_0
- r-dichromat=2.0_0=r3.3.1_2
- r-digest=0.6.9=r3.3.1_0
- r-ggplot2=2.1.0=r3.3.1_0
- r-gtable=0.2.0=r3.3.1_0
- r-labeling=0.3=r3.3.1_2
- r-magrittr=1.5=r3.3.1_2
- r-mass=7.3_45=r3.3.1_0
- r-munsell=0.4.3=r3.3.1_0
- r-plyr=1.8.4=r3.3.1_0
- r-rcolorbrewer=1.1_2=r3.3.1_2
- r-rcpp=0.12.5=r3.3.1_0
- r-reshape2=1.4.1=r3.3.1_2
- r-scales=0.4.0=r3.3.1_0
- r-stringi=1.1.1=r3.3.1_0
- r-stringr=1.0.0=r3.3.1_0
- readline=6.2=2
- requests=2.11.1=py35_0
- scipy=0.18.1=np111py35_0
- seaborn=0.7.1=py35_0
- setuptools=27.2.0=py35_0
- simplegeneric=0.8.1=py35_1
- sip=4.18=py35_0
- six=1.10.0=py35_0
- snakemake=3.8.2=py35_0
- sqlite=3.13.0=0
- terminado=0.6=py35_0
- tk=8.5.18=0
- tornado=4.4.1=py35_0
- traitlets=4.3.0=py35_0
- urllib3=1.12=py35_0
- wcwidth=0.1.7=py35_0
- wheel=0.29.0=py35_0
- widgetsnbextension=1.2.6=py35_0
- wrapt=1.10.6=py35_0
- xz=5.2.2=0
- yaml=0.1.6=0
- zeromq=4.1.4=0
- zlib=1.2.8=3
- pip:
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.0
  - nb-anacondacloud==1.2.0
  - nb-conda==2.0.0
  - nb-conda-kernels==2.0.0
  - prompt-toolkit==1.0.3

